version: "3"

services:

  mongo:
    image: mongo:4
    ports:
      - 27017
    environment:
      - MONGODB_USER=""
      - MONGODB_PASS=""
    command:
      mongod

  e-champ-install:
    build: ./e-champ-server
    image: e-champ-server
    environment:
      - MONGO_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
    command:
       node console/install

  blog-install:
    build: ./evado-app-blog
    image: evado-app-blog
    environment:
      - MONGO_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
    command:
       node console/install

  neural-net-install:
    build: ./neural-net
    image: neural-net
    environment:
      - MONGO_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
    command:
       node console/install

  e-champ:
    image: e-champ-server
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    command:
       node console/docker

  blog:
    image: evado-app-blog
    ports:
      - 3001:3000
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    command:
       node console/docker

  neural-net:
    image: neural-net
    ports:
      - 3002:3000
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    command:
       node console/docker