version: "3"

services:

  mongo:
    image: mongo:5
    ports:
      - 27017
    environment:
      - MONGODB_USER=""
      - MONGODB_PASS=""
    command:
      mongod

  e-champ-install:
    build: ../e-champ-server
    image: e-champ-server
    environment:
      - MONGO_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
    command:
       node console/install --config demo

  party-en-install:
    build: ../party-en
    image: party-en
    environment:
      - MONGO_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
    command:
       node console/install --config demo

  neural-net-install:
    build: ../neural-net
    image: neural-net
    environment:
      - MONGO_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
    command:
       node console/install --config demo

  e-champ:
    image: e-champ-server
    ports:
      - 80:3000
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    command:
       node console/docker --config demo --env production

  party-en:
    image: party-en
    ports:
      - 8080:3000
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    command:
       node console/docker --config demo --env production

  neural-net:
    image: neural-net
    ports:
      - 8081:3000
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    command:
       node console/docker --config demo --env production